// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/get-my-profile.ts
import { createClient } from "npm:@supabase/supabase-js@^2.103.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_my_profile_default = defineTool({
  name: "get_my_profile",
  title: "Get my patient profile",
  description: "Return the patient record for the currently signed-in Tooth Haven user (matched by phone number).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const claims = ctx.getClaims();
    const phone = claims?.phone;
    const email = claims?.email ?? ctx.getUserEmail();
    const sb = supabaseForUser(ctx);
    let query = sb.from("patients").select("id,name,phone,email,date_of_birth,gender,address").limit(1);
    if (phone) query = query.eq("phone", phone);
    else if (email) query = query.eq("email", email);
    else return { content: [{ type: "text", text: "No phone or email on session" }], isError: true };
    const { data, error } = await query.maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "No patient record found for this account." }] };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { patient: data }
    };
  }
});

// src/lib/mcp/tools/list-my-appointments.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.103.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^4.4.3";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
async function getPhone(ctx) {
  const claims = ctx.getClaims();
  return claims?.phone ?? null;
}
var list_my_appointments_default = defineTool2({
  name: "list_my_appointments",
  title: "List my appointments",
  description: "List the signed-in patient's appointments at Tooth Haven Dental Care, most recent first.",
  inputSchema: {
    status: z.enum(["pending", "confirmed", "completed", "cancelled", "all"]).optional().describe("Filter by appointment status. Defaults to all."),
    limit: z.number().int().min(1).max(50).optional().describe("Max rows to return (default 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const phone = await getPhone(ctx);
    if (!phone) return { content: [{ type: "text", text: "Sign in with a phone number to view appointments." }], isError: true };
    const sb = supabaseForUser2(ctx);
    let q = sb.from("appointments").select("id,name,phone,service,preferred_date,preferred_time,status,notes,created_at").eq("phone", phone).order("preferred_date", { ascending: false }).limit(limit ?? 10);
    if (status && status !== "all") q = q.eq("status", status);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { appointments: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-my-prescriptions.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.103.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z2 } from "npm:zod@^4.4.3";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
async function findPatientId(sb, phone) {
  const { data } = await sb.from("patients").select("id").eq("phone", phone).maybeSingle();
  return data?.id ?? null;
}
var list_my_prescriptions_default = defineTool3({
  name: "list_my_prescriptions",
  title: "List my prescriptions",
  description: "List prescriptions issued to the signed-in patient at Tooth Haven Dental Care.",
  inputSchema: {
    limit: z2.number().int().min(1).max(50).optional().describe("Max rows to return (default 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const claims = ctx.getClaims();
    if (!claims?.phone) return { content: [{ type: "text", text: "Sign in with a phone number." }], isError: true };
    const sb = supabaseForUser3(ctx);
    const patientId = await findPatientId(sb, claims.phone);
    if (!patientId) return { content: [{ type: "text", text: "No patient record on file." }] };
    const { data, error } = await sb.from("prescriptions").select("id,rx_date,diagnosis,medications,notes,created_at").eq("patient_id", patientId).order("rx_date", { ascending: false }).limit(limit ?? 10);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { prescriptions: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-my-invoices.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.103.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z3 } from "npm:zod@^4.4.3";
function supabaseForUser4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_my_invoices_default = defineTool4({
  name: "list_my_invoices",
  title: "List my invoices",
  description: "List invoices billed to the signed-in patient at Tooth Haven Dental Care.",
  inputSchema: {
    limit: z3.number().int().min(1).max(50).optional(),
    status: z3.enum(["draft", "sent", "paid", "cancelled", "all"]).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, status }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const claims = ctx.getClaims();
    if (!claims?.phone) return { content: [{ type: "text", text: "Sign in with a phone number." }], isError: true };
    const sb = supabaseForUser4(ctx);
    const { data: patient } = await sb.from("patients").select("id").eq("phone", claims.phone).maybeSingle();
    if (!patient) return { content: [{ type: "text", text: "No patient record on file." }] };
    let q = sb.from("invoices").select("id,invoice_number,invoice_date,total,tax,discount,status,notes").eq("patient_id", patient.id).order("invoice_date", { ascending: false }).limit(limit ?? 10);
    if (status && status !== "all") q = q.eq("status", status);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { invoices: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "zymakgyfirjecxbdvtzg";
var mcp_default = defineMcp({
  name: "tooth-haven-mcp",
  title: "Tooth Haven Dental Care",
  version: "0.1.0",
  instructions: "Tools for Tooth Haven Advanced Dental Care patients. Once signed in, you can look up your patient profile, upcoming and past appointments, prescriptions, and invoices.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [get_my_profile_default, list_my_appointments_default, list_my_prescriptions_default, list_my_invoices_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
